### ISSUE TITLE
Client resizing data packets

### ISSUE THREAD

**Issue by K-shamG** [DanGravel/TFTP#14]
DATA in pic should have been 22bytes + 4 for block and opcode, but it was 516 instead. I can't get the intermediate host to re-prompt during write if this happens. 

![clientresizedata](https://cloud.githubusercontent.com/assets/15951317/20585391/e6d39106-b1c8-11e6-8e2b-591790a837ed.jpg)

**Comment by DanGravel** [comment]
Yeah... dynamically creating arrays while sending is a huge pain. Instead use getSize() in Host.java to get the length of the data.
