### ISSUE TITLE
duplicate data, Server not ignoring ACK?

### ISSUE THREAD

**Issue by K-shamG** [DanGravel/TFTP#17]
When doing a duplicate data for read, client sends a duplicate ack after receiving the data, but it doesn't look like server is ignoring it. Instead, it sends the data again in response. 

![server2](https://cloud.githubusercontent.com/assets/15951317/20612559/477e820c-b289-11e6-91b5-5e83bc189f2e.jpg)

**Comment by br0wncrust4cean** [comment]
Please confirm if you were testing on the repromptErrorSim branch. Your server is outdated if that's the case.

**Comment by br0wncrust4cean** [comment]
Imma close this cause this is not the problem.
