### ISSUE TITLE
Client and Server stuff

### ISSUE THREAD

**Issue by K-shamG** [DanGravel/TFTP#20]
- have to check whether packet is an ack or data and if that was what is expected (if not, should send invalid opcode packet)
- I didn't see in either whether there is a check for if they receive an error packet; this is probably why the file is staying open, one side keeps transferring packets, etc after receiving an error packet

**Comment by br0wncrust4cean** [comment]
On server side, I think the file stays open because when you get an error the server sends the error packet and then returns from the method before it closes the file. To remedy this just change the return statements to breaks, which I think I might very done already but not tested.
