### ISSUE TITLE
Client is receiving change opcode error packets wrong

### ISSUE THREAD

**Issue by br0wncrust4cean** [DanGravel/TFTP#22]
When client receives server's changed opcode error packet, sends back another error saying that it received something other than a data. Should just terminate.

**Comment by br0wncrust4cean** [comment]
This kind of error is happening pretty much whenever client has to receive an invalid opcode error. It even null pointered for some reason when testing on master.

**Comment by DanGravel** [comment]
I think i fixed it by moving checking for errors right after receiving.

**Comment by DanGravel** [comment]
Client now receives an error and terminates
